// <auto-generated />
namespace Sports4All.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class M010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M010));
        
        string IMigrationMetadata.Id
        {
            get { return "202001182023394_M010"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
